name: CI/CD Pipeline to Render Staging

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v3

      - name: Trigger Render Deployment
        run: |
          curl -X POST "https://api.render.com/deploy/srv-d8rsut4vikkc738vgt10?key=PeDzxnLwQ6g"